name: telegraf-prometheus-grafana

services:
  telegraf:
    image: telegraf:1.33.0
    container_name: telegraf
    restart: always
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8094:8094"
      - "9273:9273"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"    
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana     
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

volumes:
  prom_data: