global:
  # 全局抓取间隔时间
  scrape_interval: 15s
  # 全局抓取超时时间
  scrape_timeout: 10s
  # 全局评估规则间隔时间
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        # 抓取指标的目标地址
        - localhost:9090
  - job_name: telegraf
    static_configs:
      - targets:
        - telegraf:9273
  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000        
